on:
  push:
    branches:
      - master

jobs:
  detect_tests:
    runs-on: ubuntu-latest
    name: A workflow to test the work of DataSecure
    steps:
      
    - name: Checkout
      uses: actions/checkout@v1
      
       
    - name: Git leaks Scan
      run: |
        sudo docker run --rm --name=gitleaks ${{ secrets.gitleaks }} -v -r https://github.com/FrancisBilla/GitSecure.git --pretty     
     

